### ISSUE TITLE
Add time adjustment

### ISSUE THREAD

**Issue by MightyX3N** [Jack1424/RealTimeWeather#10]
### Is there already a request similar to this?

- [X] There are not and have never been any feature requests similar to this

### What's your suggestion?

The site https://sunrisesunset.io/ does not update their data in real time, so maybe you could add a time adjustment setting to the config, so there could be added a custom amount of time, for example +2 hours to match real time,

as you can see here: https://sunrisesunset.io/search/denmark/ it says last update was 2 hours ago

**Comment by Jack1424** [comment]
RealTimeWeather only gets the sunrise and sunset times from the current day from sunrisesunset.io, not the current time. It gets the current time from the system clock of the server that it's running on and adjusts according to the timezone in the configuration.

Realistically, RealTimeWeather doesn't need to check the sunrise and sunset times every few seconds, and I'm working on moving API requests separate from the time update code soon, but it's ok if sunrisesunset.io hasn't been updated super recently.

I could add an option to offset the time, but you're better off just changing the timezone.

**Comment by MightyX3N** [comment]
well then the plugin is not working correctly, im running the server locally developing it, the time in game says 05:02 but the time locally is 11:25,

and the ingame time dont seem to change at all

**Comment by Jack1424** [comment]
This issue was fixed with #12
