### ISSUE TITLE
Set the time of day differently depending on the season

### ISSUE THREAD

**Issue by hnwh224** [Jack1424/RealTimeWeather#2]
### Is there already a request similar to this?

- [X] There are and have never been any feature requests similar to this

### What's your suggestion?

Would be really cool because it's a bit weird when it gets dark so early in the summer months.

**Comment by Jack1424** [comment]
Great idea. I was actually considering adding this option already, but I'll bump it up on my to-do list.

**Comment by Jack1424** [comment]
I know it's been a while (probably much longer than a while), but I finally implemented syncing the sunrise and sunset times with a real-world location. I'm planning on publishing the update soon.

**Comment by Jack1424** [comment]
Done! This will be released with v1.4.0 (should be coming out soon).
