### ISSUE TITLE
Weather Settings

### ISSUE THREAD

**Issue by WisteriaZy** [Jack1424/RealTimeWeather#3]
### Have you searched the wiki and looked for existing issues for this?

- [x] This is not a common issue or cannot be fixed by the solutions provided
- [X] This issue has not been reported yet

### What's happening

The weather settings in the wiki use Longitude, but the version I'm using is ZipCode and CountryCode, which I fill in as follows
ZipCode: '62900'
CountryCode: 'CHN'
But it tells me that I made a mistake. I don't know what I wrote wrong, maybe it doesn't support China zip code? I don't know, I'm not good at English, so I use DeepL to translate my question, I hope my query can be understood correctly.
The server is 1.19.4, Paper server side. rtw version is 1.2.0.

### What's supposed to happen

It should get the weather information properly.

### Server Software

Paper

### Minecraft version

1.19.4

### Additional information

The contents of my configuration:
ZipCode: '62900'
CountryCode: 'CHN'
Log content:
[20:12:54] [Server thread/INFO]: [RealTimeWeather] Enabling RealTimeWeather v1.2.0*
[20:12:54] [Server thread/INFO]: [RealTimeWeather] Starting...
[20:12:56] [Server thread/ERROR]: [RealTimeWeather] Error when getting weather information: Zip/Country code incorrect
[20:12:56] [Server thread/ERROR]: [RealTimeWeather] Please check that the values set in the config file are correct
[20:12:56] [Server thread/ERROR]: [RealTimeWeather] Disabling weather sync...
[20:12:56] [Server thread/INFO]: [RealTimeWeather] Started!

**Comment by Jack1424** [comment]
It looks like you're using the Alpha-3 country code. RealTimeWeather only supports Alpha-2 country codes. For example, the Alpha-2 code for China is `CN`. Replace `CHN` with `CN` in your configuration and see if that fixes the problem.

**Comment by qing762** [comment]
Replace
```
ZipCode: '62900'
CountryCode: 'CHN'
```

to
```
Latitude: 'YOUR COUNTRY LATITUDE'
Longitude: 'YOUR COUNTRY LONGITUDE'
```

Works well for me! :)

**Comment by Jack1424** [comment]
Update RealTimeWeather to the latest version, and make sure that you delete the old configuration file (`config.yml`) so the updated one can be generated.
