### ISSUE TITLE
Half weather sync

### ISSUE THREAD

**Issue by petikwastaken** [Jack1424/RealTimeWeather#4]
### Is there already a request similar to this?

- [ ] There are and have never been any feature requests similar to this

### What's your suggestion?

Option to use normal minecraft weather system, but when it starts raining irl it starts raining in-game until it stops raining irl then go back to using normal minecraft weather system.
I think this would be useful, because you dont want to rain(in-game) the whole time you play,  when you live in places where doesn't rain a lot.

**Comment by Jack1424** [comment]
I'm not sure that I understand what you're suggesting.

Right now RealTimeWeather will make it so the weather in-game always matches the weather of your set real-world location. I'm not planning on adding any more advanced logic than this to this plugin.
