### ISSUE TITLE
file

### ISSUE THREAD

**Issue by hey122112** [Jack1424/RealTimeWeather#5]
### Is there already a request similar to this?

- [X] There are and have never been any feature requests similar to this

### What's your suggestion?

won't let me download the file and i'm running minecraft 1.8.8 server

**Comment by Jack1424** [comment]
You can download the latest version of RealTimeWeather from this link: [https://github.com/Jack1424/RealTimeWeather/releases/download/v1.3.0/RealTimeWeather-1.3.0.jar](https://github.com/Jack1424/RealTimeWeather/releases/download/v1.3.0/RealTimeWeather-1.3.0.jar)
