### ISSUE TITLE
Weather Settings

### ISSUE THREAD

**Issue by BT115C4** [Jack1424/RealTimeWeather#6]
### Have you searched the wiki and looked for existing issues for this?

- [X] This is not a common issue or cannot be fixed by the solutions provided
- [ ] This issue has not been reported yet

### What's happening

Hello! When will the version of the plugin that uses latitude and longitude to get the weather be ready? Because the 1.2.0 version of the plugin doesn't work for my country. I tried to put in the zipcode for my area of the country, but it doesn't work.Getting the weather via zipcode seems to only work in the US?My country is China.But I really want to use it on my server!This was translated by DeepL, please contact me if anything is unclear!

### What's supposed to happen

Weather can be obtained normally by filling in the US zipcode.This was translated by DeepL, please contact me if anything is unclear!

### Server Software

Spigot

### Minecraft version

1.18.2

### RTW configuration

ZipCode: '100000' CountryCode: 'CN'

**Comment by Jack1424** [comment]
I've changed the weather location settings from using zip codes and country codes to using longitude and latitude so you should be able to use it now. Just update RealTimeWeather to the latest version, and make sure that you delete the old configuration file (config.yml) so the updated one can be generated.
